[connections.gsheets]
spreadsheet = "16PhsJzo4askm-8iT0tMuBjsLpTEegCRDFFl4AUng6Hg"
type = "service_account"
project_id = "pr-dashboard-485514"
private_key_id = "0e0319377347243c58d6ffdd6906c2f5984d612a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC3csM0QO0ofjBs
b9PcQAjxZKEQnXkWD4YnYfsCppgK5kaHnEDZtC4Ww7gLxHroVCom26rizlh4V/f0
ICQ3sOBlzuKrDZK8b864MIXYBLYa6eyLUX3pisJBz9wyUefJug9TPFPPUUrxk1vc
Ia/eW6FpdBATDLBNlrmvvXvGCoPydNoxFtCEe6fKO+XZXEz6dMPnWhhrEO2EpWGG
hDQbvL+mJT+ZR1THWc6llrbj9yQVtnwqKujtqODH+Rl/7oTfAiZgNxVTL28ZPP3u
I94YARw5b5j8b1s4Xy4WO7Fr3eCqhMuh+hnDfD/ynmp9RBXGgHYcVVH55uarCrMi
pvTlICArAgMBAAECggEAEUBtJBZbrIcFdcUkdt4yGRq+B4p6RH1W6pA3zf2DEeSq
9ajXnmw9OK3U5Te9LpPFAlzTxWWOA1npJbT6GEn9fbAxjSWHIEp2yx02ZmS3CBvp
6gYoDFTyGhn6mrmCI0HonArHKkQlA0fjh8rxN5IwFp3avyKJLUVt6/LVV3/4qE3K
eP1SjGxgU7sczykvX4XTp/kxaBD3vC6LIx/qan99CaYuWAOh4i3OPaxzfRxdSgUZ
6mJYJwvQn7gWV1OeAa1EoD3lgw9yrjNv0z3e54RJtVpSiY+TTNP920xMf1E/TIAa
qv6KIo4uNXjl6VDCS1Wp4kTyyI/Hehuw5hTCnU40oQKBgQDaesszHSf5duxOjlcR
d8RlLW8BYPshuofUrrN25b1sqnDSsjEeIFMw6y5PlrYgqba1ZfM4hb1qQ531yXOp
DQqXLuvmDb/9zFYlCXeQbb6O1Q+zej5JaS4a/dgYgCApmh2kqYWvCnMa59C9Jo5f
Hmx3PNUfdFqFmrlJz/mXtBmOIQKBgQDW89rcYKK3M/d9OV4O4I+25aKs0Xtz1d9p
SYcj/39sTSEQ4gxFBK1c+QKVG5Fe+zk7WQxIA5FJKf1/oYwFOjTwRzXi6DbDG8It
AyVu7Vdfsgioywk/iexka3a0u2cLCrIUATemUVF/jVYRp9+F39DSMFiIvs38QgYl
W2LvbxbsywKBgHdQA9RAIep8ZYRo+2eQrnJKo4pvOfYrda5SUbOmtxG26rJFmclI
AeZ/KOVR+thPlnXt3SuK7ewwTP1DLKSveI8jkrQp4iVqB8lmKCN5q005Ub/EDGvu
wrz+z5phri7J+VJJObZj0IRrAHWrrqiHZtifIgxxcFXyLyn+J+IO+r3BAoGARWpC
h2B9q4QQrFPWWB+UyY+m1QBhSasLlsiz56Ae2i6eOwGEzNUR1zBi8RwR+gZPGSdM
nATq6iGxR4I34YhGiEG22Sv8Y02Xi0m00Pm8eZ7YxQmsVuSHfnZlwz+xqxMtJuCt
w/wGwZY28USxHl6E5RvPu3lCs+/uZCn67S+Gy7kCgYAVvwZTsVZU+xTf/A+rNBDo
Q8dqIdMlKlawG4f/MNgfof+Cs9YNed5uz0wniLQKbluFqui9jEQCTBrwi5e5Mj3Z
9dmhkD99bOoHQNXU+MTGuABoc1FYH3jFFbRn4ZSwkOXClIBoagq7mFMvgjwwvKSE
sUd5cPTxHf3H5kx0ACyFCQ==
-----END PRIVATE KEY-----"""
client_email = "pr-sheet-access@pr-dashboard-485514.iam.gserviceaccount.com"
client_id = "101171214319467978424"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pr-sheet-access%40pr-dashboard-485514.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
